### ISSUE TITLE
languagetool implementation

### ISSUE THREAD

**Issue by scotticles** [jacquetc/skribisto#1]
This is just an idea, i use this with libreoffice.
https://www.languagetool.org/

see their github and how its made, would be an awesome feature to have.

**Comment by jacquetc** [comment]
Hello, 

I only just saw your comment. I'm not used to GitHub yet ! 
We can try to add this feature as a plugin. I know of another similar tool , Druide Antidote (proprietary), which can be useful to add for french people...

I don't know yet how to wrap java in python...  I'll first implement the plugin "slot" so someone more skilled can have fun creating this sort of plugin !

**Comment by scotticles** [comment]
I noticed it did a cli version maybe the plugin could push text to that and get a return. Im not sure. I've been using it with libreoffice writer and it picks up stuff that helps when writing better sentences. Just very useful. I need to get time and try out this new version your building, it sounds like its going to be feature rich.

**Comment by jacquetc** [comment]
Cli version would work only with Linux, but it would be a start. Thanks
To try Plume, follow the steps in the readme. I'm a bit busy this week and the next, but feel free to mail me if you want. 
Right now, Plume seems quite... empty ? ... as I'm concentrating on the skeleton . It's easier and easier to add actions, buttons, ... 
Ah, I have to freeze the plugin entry points soon and make it easier to write them. Like a good documentation...

**Comment by scotticles** [comment]
I am close, had to install a few more packages i think and cx-freeze for python3 had a trick to do to make that work.

I get this:

```
scott@scott-xfce ~/plume-creator/build/exe.linux-x86_64-3.4 $ ./plume-creator 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.4-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "src/plume/plume.py", line 1, in <module>
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2214, in _find_and_load
    return _find_and_load_unlocked(name, import_)
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2203, in _find_and_load_unlocked
    module = _SpecMethods(spec)._load_unlocked()
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
    return self._load_backward_compatible()
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
    spec.loader.load_module(spec.name)
  File "src/plume/ui_converter.py", line 66, in <module>
  File "src/plume/ui_converter.py", line 25, in build_forms
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2214, in _find_and_load
    return _find_and_load_unlocked(name, import_)
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2203, in _find_and_load_unlocked
    module = _SpecMethods(spec)._load_unlocked()
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
    return self._load_backward_compatible()
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
    spec.loader.load_module(spec.name)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 43, in <module>
    from .Compiler import indenter, compiler
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2214, in _find_and_load
    return _find_and_load_unlocked(name, import_)
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2201, in _find_and_load_unlocked
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'PyQt5.uic.Compiler'
```

Thats the weird part, i have pyqt5 and in the shared libs for uic is Comiler/compiler.py etc.., any ideas?

**Comment by jacquetc** [comment]
Follow the instructions on the Readme.md (I recently filled it) to launch Plume . The setup.py is "in development" , maybe the last version is ok although.

**Comment by scotticles** [comment]
got it, very cool. I like what you did with that overview panning. I haven't done much python so im going to poke around the code a bit and see how it works with Qt. I've done c++ qt and its fun stuff. If i feel like im ready i may ask for a simple task to help you out. I like what you are doing.

**Comment by jacquetc** [comment]
As for now, Plume isn't very documented. Be careful of the MVC pattern and of the "subscriber" modules in "data" and "core". If you have questions, you can contact me directly at cyril.jacquet@plume-creator.eu  .
